name: Reusable CI

on:
  workflow_call:
    inputs:
      test:
        type: string

concurrency:
  group: testgroup
  cancel-in-progress: false
  
jobs:
  build1:
    if: inputs.name == 'test123'
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "name = ${{ inputs.name }}"

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "description = ${{ inputs.description }}"
        

  build3:
    needs: [build1,build2]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: smars006/test

      - name: sleep
        run: sleep 500
        
